package com.sigecap.sigecaprest.util;

public interface BusinessMsgError {

    String ERROR_USUARIO_ROL = "EL USUARIO NO TIENE EL ROL ADECUADO";
    String ERROR_USUARIO_INACTIVO = "EL USUARIO SE ENCUENTRA INACTIVO";
    String ERROR_USUARIO_INCORRECTO = "EL USUARIO O CLAVE NO COINCIDE";
    String ERROR_RUC_INCORRECTO = "EL RUC NO TIENE UN VALOR VALIDO";
    String ERROR_DATOS_INCOMPLETOS = "NO SE TIENE TODOS LOS DATOS COMPLETOS A ENVIAR";
    String ERROR_CODIGO_PAGO_NO_EXISTE = "EL CODIGO DE PAGO NO EXISTE";
    String ERROR_CODIGO_PAGO_PROCESADO = "EL CODIGO DE PAGO YA FUE PROCESADO";
    String ERROR_CODIGO_PAGO_LIMITE_CARACTERES = "EL CODIGO DE PAGO TIENE MAYOR A 8 DIGITOS";
    String ERROR_ARCHIVOS_INCOMPLETOS = "NO SE TIENE LOS 3 ARCHIVOS NECESARIOS";
    String ERROR_ARCHIVOS_TAMAÑO = "EL TAMAÑO DEL ARCHIVO ES INCORRECTO";
    String ERROR_NO_DATA_RUC = "NO HAY INFORMACION PARA ESE NUMERO DE RUC";
    String ERROR_NUMERO_SERIE_LIMITE_CARACTERES = "LA SERIE Y NUMERO SUPERAN LOS 20 DIGITOS";
    String ERROR_ARCHIVO_NOMBRE_LIMITE_CARACTERES = "EL NOMBRE DEL ARCHIVO SUPERA LOS 200 DIGITOS";
    String ERROR_ARCHIVO_FORMATO = "EL TIPO DE FORMATO NO PERMITE EN EL ARCHIVO";
    String ERROR_ARCHIVO_CADA_UNO = "SOLO SE PERMITE UN FORMATO POR CADA ARCHIVO";
}
